name: Github Pages Astro CI

on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]

env:
  API_TOKEN: ${{ secrets.NEW_ACCESS_TOKEN }}
  MAIN_REPO_TOKEN: ${{ secrets.NEW_ACCESS_TOKEN }} # this is a special github token that has full access.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.3
      - run: |
          cd scripts
          echo GITHUB_API_TOKEN=$API_TOKEN > .env
          deno --version
          deno run --allow-read --allow-write --allow-env --allow-net mods.ts 
          rm -rf .env
          cd ../

      - uses: actions/setup-node@v2
        name: Update node
        with:
          node-version: '14'

      # Install dependencies with npm
      - name: Install dependencies
        run: npm install

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build
        run: |
          npm run build
      # Push to your pages repo
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist