name: Build Main Site
# Don't want to burn my private minutes at this point
on:
  push:
    branches:
      - master
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 21 * * 5'

env:
  githubEmail: davidli012345@gmail.com
  deployToRepo: FriendlyUser.github.io
  GITHUB_API_TOKEN: ${{ secrets.NEW_ACCESS_TOKEN }}
  MAIN_REPO_TOKEN: ${{ secrets.NEW_ACCESS_TOKEN }} # this is a special github token that has full access.

jobs:
  make_website:
    name: Generate Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: denolib/setup-deno@v2
      #   with:
      #     deno-version: v1.3
      # - run: |
      #     cd scripts
      #     ls
      #     echo GITHUB_API_TOKEN=$GITHUB_API_TOKEN > .env
      #     deno --version
      #     deno run --allow-read --allow-write --allow-env --allow-net mods.ts
      #     rm -rf .env
      #     cd ../

      - uses: actions/setup-node@v2
        name: Update node
        with:
          node-version: '16'

      - name: install astro
        run: npm install

      - name: update config
        run: |
          sed -i 's/astro-tech-blog\///g' astro.config.mjs
          npm run build
      
      - name: update gh pages
        run: |
          cd dist
          git init
          echo google.com, pub-2479144310234386, DIRECT, f08c47fec0942fa0 > ads.txt
          git config --global user.email "davidli012345@gmail.com"
          git config --global user.name "David Li"
          echo > .nojekyll
          git add . -f
          git commit -m "Publishing GitHub Pages ***NO_CI***"
          git remote add origin https://github.com/FriendlyUser/FriendlyUser.github.io.git
          git remote set-url origin https://FriendlyUser:$MAIN_REPO_TOKEN@github.com/FriendlyUser/FriendlyUser.github.io.git
          git push origin master --force
          cd ../

        