name: Publish To Medium
# Don't want to burn my private minutes at this point
on:
  push:
    branches:
      - master
      - main

env:
  MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
jobs:
  make_website:
    name: Generate Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: update config
        run: |
          python scripts/upload_to_medium.py
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.MAIN_REPO_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist


        