name: Publish To Medium
# Don't want to burn my private minutes at this point
on:
  push:
    branches:
      - master
      - main

env:
  MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
jobs:
  make_website:
    name: Generate Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: upload to medium
        run: |
          python -m pip install python-frontmatter requests python-dateutil
          python scripts/upload_to_medium.py
      
      # push back to repo all txt files
      - name: update repo
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add scripts/*.txt
          git commit -m "Update Medium Posts"
          git push
      
      # push back to repo all txt files
      


        
